---
# Parameters:
# - security_device: Device to add. Has subfields:
#   - name: Human-friendly name of the device, like "OpenSC PKCS Module"
#   - lib: Path to the library implementing the device, e.g.,
#	/usr/lib/libfoo.so

- name: "Security device {{ security_device.name }}"
  vars:
    profile_subdir: "{{ firefox_dir }}/{{ profiles.profiles[profile].path | default('dummy') }}"
  blockinfile:
    path: "{{ profile_subdir }}/pkcs11.txt"
    block: |
      name={{ security_device.name }}
      library={{ security_device.lib }}
    create: yes
